apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-driver-deployment
  labels:
    app: my-driver-deployment
spec:
  selector:
     matchLabels:
       app: my-driver-deployment
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-driver-deployment
    spec:
      containers:
        - image: haoyup/my-driver:v6
          imagePullPolicy: Always
          name: my-driver-deployment
          env:
            - name: JUPYTER_NOTEBOOK
              value: "http://my-jupyter-notebook"

          ports:
            - containerPort: 23333