apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spark
  labels:
    app: my-spark
spec:
  selector:
     matchLabels:
       app: my-spark
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-spark
    spec:
      containers:
        - image: bde2020/spark-master:2.4.1-hadoop2.7
          imagePullPolicy: Always
          name: my-spark
          ports:
            - containerPort: 8080